# Generated by Django 5.2 on 2025-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('primary_color', models.CharField(default='#3490dc', max_length=20, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#ffed4a', max_length=20, verbose_name='Secondary Color')),
                ('accent_color', models.CharField(default='#f66d9b', max_length=20, verbose_name='Accent Color')),
                ('font_family', models.CharField(default="'Inter', sans-serif", max_length=100, verbose_name='Font Family')),
                ('heading_font_family', models.CharField(blank=True, max_length=100, verbose_name='Heading Font Family')),
                ('container_width', models.CharField(default='1200px', max_length=20, verbose_name='Container Width')),
                ('custom_css', models.TextField(blank=True, verbose_name='Custom CSS')),
                ('custom_js', models.TextField(blank=True, verbose_name='Custom JavaScript')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='theme/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='theme/favicons/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
