# Generated by Django 5.2 on 2025-04-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='Open Graph title')),
                ('og_description', models.TextField(blank=True, verbose_name='Open Graph description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='Open Graph image')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Featured Image')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
