# Generated by Django 5.2 on 2025-04-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Widget Area',
                'verbose_name_plural': 'Widget Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('widget_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('recent_posts', 'Recent Posts'), ('popular_posts', 'Popular Posts'), ('categories', 'Categories'), ('tags', 'Tags'), ('newsletter', 'Newsletter'), ('social', 'Social Links'), ('image', 'Image'), ('hero', 'Hero'), ('features', 'Features'), ('featured_posts', 'Featured Posts'), ('call_to_action', 'Call to Action'), ('custom', 'Custom')], max_length=20, verbose_name='Widget Type')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Settings')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='widgets.widgetarea', verbose_name='Widget Area')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['area', 'order'],
            },
        ),
    ]
